name: GFSLT-VLP
data:
  train_label_path: ./data/Phonexi-2014T/labels.train
  dev_label_path: ./data/Phonexi-2014T/labels.dev
  test_label_path: ./data/Phonexi-2014T/labels.test
  img_path: ./data/PHOENIX-2014-T/features/fullFrame-210x260px/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  transformer:  ./pretrain_models/MBart_trimmed
  visual_encoder: ./pretrain_models/mytran
  sign_proj: True
