name: GFSLT-VLP
data:
  train_label_path: ./data/CSL-Daily/WordLevel/labels.train
  dev_label_path: ./data/CSL-Daily/WordLevel/labels.dev
  test_label_path: ./data/CSL-Daily/WordLevel/labels.test
  img_path: ./data/CSL-Daily/sentence/frames_256x256px/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  transformer:  ./pretrain_models/CSL/MBart_trimmed
  visual_encoder: ./pretrain_models/CSL/mytran
  sign_proj: True
